name: publish
env:
  NODE_VERSION: 21.7.3
  PNPM_VERSION: 9.12.1
on:
  workflow_dispatch:
  # pull_request:
  #   branches: [main]
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    # expose output
    outputs:
      published: ${{steps.changesets.outputs.published}}
    steps:
      - name: Cleanup
        shell: bash
        run: |
          echo "Cleaning up workspace"
          sudo rm -rfv ${{ github.workspace }}
          mkdir -p ${{ github.workspace}}

      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=${{ secrets.SCOPED_YOLO }}
            @forkingidiots:registry=https://npm.pkg.github.com
          EOF

      - name: create release pull
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{secrets.SCOPED_YOLO}}

  boom:
    runs-on: ubuntu-latest
    needs: publish
    if: needs.publish.outputs.published == 'true'
    steps:
      - name: boom 💥
        shell: bash
        run: |
          echo "🎉 New version published successfully!"
          echo "💥 BOOM! Time to celebrate!"
